# Generated by Django 5.2.6 on 2025-10-29 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('precio_por_persona', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actividades/')),
                ('dias_disponibles', models.CharField(help_text='Ej: Lunes, Martes, Miércoles, Jueves, Viernes', max_length=100)),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='alojamientos/')),
                ('precio_por_persona', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('habitaciones', models.IntegerField(default=1)),
                ('entrada_salida', models.CharField(help_text='Ej: Check-in 14:00 / Check-out 10:00', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='alquileres/')),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habitaciones', models.IntegerField(default=1)),
                ('baños', models.IntegerField(default=1)),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('tipo_alquiler', models.CharField(choices=[('Casa', 'Casa'), ('Cabaña', 'Cabaña'), ('Departamento', 'Departamento'), ('Villa', 'Villa'), ('Loft', 'Loft'), ('Penthouse', 'Penthouse')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='paquetes/')),
                ('duracion', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oferta', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('destino', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='transportes/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad', models.IntegerField()),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('duracion', models.CharField(max_length=50)),
                ('tipo_traslado', models.CharField(choices=[('Desde aeropuerto', 'Desde aeropuerto'), ('Hacia aeropuerto', 'Hacia aeropuerto'), ('Traslado urbano', 'Traslado urbano')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('precio_por_persona', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_salida', models.DateField()),
                ('horario_salida', models.TimeField()),
                ('fecha_regreso', models.DateField()),
                ('horario_regreso', models.TimeField()),
                ('clase', models.CharField(max_length=50)),
                ('aerolinea', models.CharField(max_length=100)),
                ('detalles', models.TextField(blank=True)),
                ('escala', models.CharField(blank=True, help_text='Ej: 1 escala en Lima', max_length=100)),
                ('duracion', models.CharField(help_text='Duración total del vuelo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Carrito_app.actividad')),
                ('alojamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Carrito_app.alojamiento')),
                ('alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Carrito_app.alquiler')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrito_app.carrito')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Carrito_app.paquete')),
                ('vuelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Carrito_app.vuelos')),
            ],
        ),
    ]
