# Generated by Django 5.2.6 on 2025-10-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
