# Generated by Django 5.2.6 on 2025-10-30 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Carrito_app.transporte'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Carrito_app.actividad'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='alojamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Carrito_app.alojamiento'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='alquiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Carrito_app.alquiler'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Carrito_app.paquete'),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='vuelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Carrito_app.vuelos'),
        ),
    ]
