# Generated by Django 5.2.6 on 2025-10-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0002_paquete_activo_paquete_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='actividades/'),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alojamientos/'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alquileres/'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes/'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='transportes/'),
        ),
    ]
