# Generated by Django 5.2.6 on 2025-10-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0002_itemcarrito_transporte_alter_itemcarrito_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
