# Generated by Django 5.2.6 on 2025-11-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0004_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelos',
            name='region',
            field=models.CharField(choices=[('Sudamérica', 'Sudamérica'), ('Europa', 'Europa'), ('Norteamérica', 'Norteamérica'), ('Medio Oriente', 'Medio Oriente'), ('Centroamérica', 'Centroamérica'), ('Asia', 'Asia'), ('África', 'África')], default='Sudamérica', max_length=50),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='categoria',
            field=models.CharField(choices=[('Aventura', 'Aventura'), ('Gastronomía', 'Gastronomía'), ('Relajación', 'Relajación'), ('Culturales', 'Culturales'), ('Naturales', 'Naturales')], default='Aventura', max_length=50),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='tipo',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Hostel', 'Hostel'), ('Resort', 'Resort')], default='Hotel', max_length=50),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='tipo_alquiler',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Cabaña', 'Cabaña'), ('Villa', 'Villa'), ('Loft', 'Loft')], default='Casa', max_length=50),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='categoria',
            field=models.CharField(choices=[('Familiares', 'Familiares'), ('Grupales', 'Grupales'), ('Luna de miel', 'Luna de miel'), ('Aventura', 'Aventura'), ('Culturales', 'Culturales'), ('Relax', 'Relax'), ('Spa', 'Spa')], default='Familiares', max_length=50),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='tipo',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], default='Nacional', max_length=50),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='tipo',
            field=models.CharField(choices=[('Auto', 'Auto'), ('Auto Premium', 'Auto Premium'), ('Mini Van', 'Mini Van'), ('Bus', 'Bus'), ('Van', 'Van')], default='Auto', max_length=50),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='tipo_traslado',
            field=models.CharField(choices=[('Desde aeropuerto', 'Desde aeropuerto'), ('Hacia aeropuerto', 'Hacia aeropuerto'), ('Traslado urbano', 'Traslado urbano')], default='Traslado urbano', max_length=50),
        ),
        migrations.AlterField(
            model_name='vuelos',
            name='aerolinea',
            field=models.CharField(choices=[('Aerolíneas Argentinas', 'Aerolíneas Argentinas'), ('LATAM Airlines', 'LATAM Airlines'), ('Emirates', 'Emirates'), ('Lufthansa', 'Lufthansa'), ('Iberia', 'Iberia'), ('Qatar Airways', 'Qatar Airways'), ('Air France', 'Air France'), ('KLM', 'KLM'), ('Turkish Airlines', 'Turkish Airlines'), ('United Airlines', 'United Airlines'), ('British Airways', 'British Airways'), ('Copa Airlines', 'Copa Airlines'), ('Delta Air Lines', 'Delta Air Lines'), ('American Airlines', 'American Airlines'), ('Swiss Air', 'Swiss Air'), ('Alitalia', 'Alitalia'), ('Air Canada', 'Air Canada'), ('Air Europa', 'Air Europa'), ('Etihad Airways', 'Etihad Airways'), ('Ethiopian Airlines', 'Ethiopian Airlines'), ('Singapore Airlines', 'Singapore Airlines'), ('ANA Japan', 'ANA Japan'), ('Thai Airways', 'Thai Airways'), ('EVA Air', 'EVA Air'), ('South African Airways', 'South African Airways'), ('Finnair', 'Finnair'), ('Virgin Atlantic', 'Virgin Atlantic')], default='Aerolíneas Argentinas', max_length=100),
        ),
        migrations.AlterField(
            model_name='vuelos',
            name='clase',
            field=models.CharField(choices=[('Económica', 'Económica'), ('Premium Económica', 'Premium Económica'), ('Business', 'Business'), ('Primera Clase', 'Primera Clase')], default='Económica', max_length=50),
        ),
    ]
