# Generated by Django 5.2.6 on 2025-11-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0005_vuelos_region_alter_actividad_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='tipo',
            field=models.CharField(choices=[('Auto', 'Auto'), ('Auto Premium', 'Auto Premium'), ('Mini Van', 'Mini Van'), ('Bus', 'Bus'), ('Van', 'Van'), ('Limusina', 'Limusina'), ('Bicicleta', 'Bicicleta'), ('Yate', 'Yate'), ('Helicóptero', 'Helicóptero'), ('Scouter', 'Scouter'), ('Tren', 'Tren')], default='Auto', max_length=50),
        ),
    ]
