# Generated by Django 5.2.6 on 2025-11-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0006_alquiler_activo_alter_transporte_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='fecha',
            new_name='fecha_compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
