# Generated by Django 5.2.6 on 2025-11-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0007_rename_fecha_compra_fecha_compra_compra_comprobante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='comprobante',
        ),
        migrations.AddField(
            model_name='compra',
            name='items',
            field=models.ManyToManyField(to='Carrito_app.paquete'),
        ),
    ]
