# Generated by Django 5.2.6 on 2025-11-06 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0008_remove_compra_comprobante_compra_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='items',
        ),
        migrations.AddField(
            model_name='carrito',
            name='actividades',
            field=models.ManyToManyField(blank=True, to='Carrito_app.actividad'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='alojamientos',
            field=models.ManyToManyField(blank=True, to='Carrito_app.alojamiento'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='alquileres',
            field=models.ManyToManyField(blank=True, to='Carrito_app.alquiler'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='paquetes',
            field=models.ManyToManyField(blank=True, to='Carrito_app.paquete'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='transportes',
            field=models.ManyToManyField(blank=True, to='Carrito_app.transporte'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='vuelos',
            field=models.ManyToManyField(blank=True, to='Carrito_app.vuelos'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
