# Generated by Django 5.2.6 on 2025-11-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0009_remove_compra_items_carrito_actividades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('en_stock', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
