# Generated by Django 5.2.6 on 2025-11-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0011_alquiler_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
