# Generated by Django 5.2.6 on 2025-11-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0012_carrito_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
