# Generated by Django 4.2.16 on 2025-09-16 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.CharField(help_text='Ruta a la imagen desde la carpeta static. Ej: Carrito_app/img/nombre_archivo.jpg', max_length=200)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='Carrito_app.destino')),
            ],
        ),
    ]
