
# Generated by Django 4.2.13 on 2024-09-16 18:59

from django.db import migrations

def update_image_paths(apps, schema_editor):
    Paquete = apps.get_model('Carrito_app', 'Paquete')
    
    replacements = {
        'Carrito_app/img/Cabaña en Bariloche.jpg': 'Carrito_app/img/cabana_en_bariloche.jpg',
        'Carrito_app/img/Cataratas del Iguazú.jpg': 'Carrito_app/img/cataratas_de_iguazu.jpg',
        'Carrito_app/img/Escapada Tropical Maldivas.jpg': 'Carrito_app/img/escapada_tropical_maldivas.jpg',
        'Carrito_app/img/Hotel Boutique Palermo.jpg': 'Carrito_app/img/hotel_boutique_palermo.jpg',
        'Carrito_app/img/Maravillas de Islandia.jpg': 'Carrito_app/img/maravillas_de_islandia.jpg',
        'Carrito_app/img/Minivan Familiar.jpg': 'Carrito_app/img/minivan_familiar.jpg',
        'Carrito_app/img/Resort & Spa Mendoza.jpg': 'Carrito_app/img/resort_and_spa_mendoza.jpg',
        'Carrito_app/img/Safari Fotográfico Península Valdés.jpg': 'Carrito_app/img/safari_fotografico_peninsula_valdes.jpg'
    }

    for old_path, new_path in replacements.items():
        Paquete.objects.filter(imagen=old_path).update(imagen=new_path)

class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_image_paths),
    ]
