# Generated by Django 3.2.5 on 2025-09-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrito_app', '0002_auto_20250916_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
