from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('login/', views.login_view, name='login'),
    path('verify/', views.verify_code, name='verify'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home, name='home'),
    path('acerca/', views.acerca, name='acerca'),
    path('alojamiento/', views.alojamiento, name='alojamiento'),
    path('alquileres/', views.alquileres, name='alquileres'),
    path('vuelos/', views.vuelos, name='vuelos'),
    path('paquetes/', views.paquetes, name='paquetes'),
    path('paquete/<int:paquete_id>/', views.paquete_detalle, name='paquete_detalle'),
    path('transporte/', views.transporte, name='transporte'),
    path('transporte/<int:transporte_id>/', views.transporte_detalle, name='transporte_detalle'),
    path('actividades/', views.actividades, name='actividades'),
    path('contacto/', views.contacto, name='contacto'),
    path('carrito/', views.carrito, name='carrito'),
    path('add_to_cart/<int:paquete_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update_cart/<int:paquete_id>/', views.update_cart, name='update_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('support/', views.support, name='support'),
    path('medios_pago/', views.medios_pago, name='medios_pago'),
    path('preguntas_frecuentes/', views.preguntas_frecuentes, name='preguntas_frecuentes'),
    path('arrepentimiento/', views.arrepentimiento, name='arrepentimiento'),
    path('pago/', views.pago, name='pago'),
    path('soporte_pago/', views.soporte_pago, name='soporte_pago'),
    path('terminos/', views.TerminosView.as_view(), name='termino_condiciones'),
    path('privacidad/', views.PrivacidadView.as_view(), name='privacidad'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('order-history/', views.order_history, name='order_history'),
    path('login_api/', views.login_api_view, name='login_api'),
]
